USE mulesoft_database;

CREATE table products
(
    product_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    product_name VARCHAR(50),
    price DOUBLE,
    quantity INT,
    description VARCHAR(100),
    category VARCHAR(50),
    CHECK (quantity >= 0)
) Engine = InnoDB;

DELIMITER //
CREATE TRIGGER qty_not_zero
BEFORE UPDATE ON products
FOR EACH ROW
BEGIN
    IF NEW.quantity < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Quantity cannot be negative';
    END IF;
END//

DELIMITER ;

INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '56.8', 20, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '49.63', 18, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '62.13', 12, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '82.5', 18, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '118.29', 7, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '133.28', 18, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '17.95', 12, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '58.12', 9, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '127.16', 19, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '52.97', 14, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '196.03', 5, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '43.64', 8, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '158.73', 7, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '130.28', 15, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '60.14', 15, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '36.32', 16, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '88.46', 19, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '119.09', 17, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '160.77', 8, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '45.33', 12, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '107.14', 7, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '35.85', 14, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '48.96', 17, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '113.86', 15, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '101.38', 13, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '181.24', 8, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '132.07', 18, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '49.15', 20, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '193.41', 6, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '174.23', 14, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '87.23', 13, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '26.48', 13, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '29.26', 13, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '70.37', 13, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '58.5', 6, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '56.55', 20, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '45.17', 17, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '122.86', 8, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '26.07', 13, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '49.3', 13, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '16.12', 7, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '38.88', 10, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '10.64', 10, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '83.74', 6, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '20.56', 7, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '33.9', 17, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '86.83', 11, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '28.25', 7, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '48.25', 6, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '45.25', 18, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '13.36', 6, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '15.64', 19, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '70.5', 12, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '77.47', 10, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '100.69', 12, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '118.18', 9, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '57.31', 17, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '120.19', 13, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '169.2', 16, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '35.36', 5, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '16.34', 20, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '156.49', 17, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '20.54', 16, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '87.5', 14, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '54.61', 9, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '52.88', 11, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '68.3', 13, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '26.48', 20, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '31.13', 14, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '43.67', 7, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '43.22', 11, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '11.44', 18, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '31.21', 19, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '92.04', 9, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '28.22', 9, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '121.18', 15, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '183.55', 19, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '51.48', 12, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '66.52', 15, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '31.86', 7, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '93.93', 17, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '85.21', 14, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '73.8', 15, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '30.91', 10, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '31.85', 20, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '85.18', 18, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '52.87', 19, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '57.79', 11, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '28.0', 14, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '29.56', 14, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '73.61', 5, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '39.2', 7, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '89.18', 14, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '28.05', 13, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '74.99', 15, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '59.69', 11, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '46.66', 9, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '32.76', 11, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '15.64', 7, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '36.54', 13, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '72.3', 15, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '41.95', 5, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '37.43', 19, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '77.52', 11, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '63.15', 9, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '72.46', 10, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '25.57', 13, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '18.65', 13, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '45.34', 18, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '53.83', 11, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '102.86', 10, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '52.01', 11, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '106.97', 11, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '14.92', 12, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '41.7', 7, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '17.08', 17, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '129.88', 10, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '12.88', 8, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '63.18', 20, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '63.01', 19, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '29.33', 5, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '97.84', 18, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '71.9', 6, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '18.93', 5, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '47.14', 5, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '30.03', 10, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '83.68', 5, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '74.89', 13, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '28.73', 17, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '41.62', 6, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '38.44', 18, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '128.47', 16, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '23.17', 8, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '187.82', 13, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '23.18', 17, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '54.58', 18, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '57.31', 8, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '78.42', 9, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '142.6', 5, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '14.93', 5, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '76.02', 13, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '95.43', 17, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '46.2', 14, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '40.91', 19, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '23.63', 5, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '27.37', 11, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '54.45', 8, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '26.01', 11, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '22.12', 16, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '44.33', 7, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '47.21', 14, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '42.03', 19, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '12.63', 16, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '52.98', 17, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '72.35', 6, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '91.51', 12, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '53.69', 9, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '43.68', 8, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '115.11', 19, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '62.37', 17, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '40.53', 12, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '14.74', 16, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '43.47', 14, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '64.17', 15, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '53.11', 20, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '93.01', 20, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '24.73', 8, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '142.94', 13, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '132.98', 18, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '92.73', 19, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '73.08', 13, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '71.08', 11, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '107.33', 8, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '130.2', 13, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '115.98', 11, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '8.2', 19, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '78.93', 20, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '23.02', 8, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '56.43', 15, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '7.53', 10, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '109.54', 18, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '79.5', 6, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '67.72', 8, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '19.84', 5, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '47.75', 11, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '55.47', 19, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '60.19', 6, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '46.29', 9, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '83.64', 18, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '36.45', 7, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '57.97', 9, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '51.78', 9, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '89.21', 9, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '108.39', 19, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '116.76', 20, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '24.26', 20, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '55.66', 5, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '137.48', 19, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '38.98', 6, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '62.52', 10, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '33.99', 7, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '91.5', 12, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '41.0', 8, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '55.96', 18, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '95.83', 7, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '43.67', 8, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '50.32', 14, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '98.07', 16, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '123.51', 12, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '54.77', 18, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '16.07', 8, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '65.64', 9, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '64.73', 8, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '30.63', 8, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '116.44', 18, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '97.37', 17, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '43.48', 13, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '33.27', 11, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '30.22', 13, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '175.29', 9, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '41.02', 7, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '71.96', 15, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '131.65', 17, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '118.68', 10, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '46.91', 14, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '23.61', 9, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '76.46', 8, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '66.61', 13, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '63.54', 9, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '174.8', 7, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '187.72', 17, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '49.63', 17, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '34.06', 7, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '18.59', 9, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '53.21', 18, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '100.68', 20, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '42.49', 18, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '40.7', 20, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '81.42', 6, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '63.72', 9, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '51.77', 7, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '39.03', 20, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '50.03', 12, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '105.12', 10, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '88.36', 5, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '101.19', 18, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '121.95', 5, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '126.69', 19, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '36.72', 19, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '33.52', 6, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '52.98', 9, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '135.52', 8, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '103.17', 20, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '82.63', 9, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '32.88', 6, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '70.84', 7, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '63.01', 7, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '169.66', 13, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '68.1', 18, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '50.88', 7, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '88.96', 11, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '71.87', 15, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '98.76', 19, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '35.13', 5, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '128.23', 8, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '90.83', 12, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '83.84', 13, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '32.48', 18, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '43.19', 19, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '119.85', 7, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '88.18', 7, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '56.49', 20, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '57.85', 12, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '44.14', 18, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '85.75', 16, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '118.85', 7, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '89.07', 7, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '46.57', 17, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '92.09', 10, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '93.25', 16, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '50.39', 18, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '102.83', 5, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '63.16', 20, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '28.06', 16, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '14.12', 10, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '20.22', 15, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '59.05', 12, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '120.79', 12, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '49.96', 9, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '170.27', 6, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '62.32', 10, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '146.17', 16, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '83.39', 9, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '24.1', 7, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '94.51', 15, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '42.78', 10, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '32.83', 17, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '36.21', 5, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '45.77', 14, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '26.59', 16, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '85.34', 19, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '136.47', 18, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '65.39', 11, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '92.44', 13, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '95.74', 12, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '31.4', 8, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '18.43', 11, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '144.13', 9, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '29.23', 18, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '133.01', 6, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '12.24', 19, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '101.81', 7, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '34.2', 20, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '30.6', 17, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '38.94', 13, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '53.38', 15, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '44.0', 11, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '60.93', 11, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '90.79', 17, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '41.76', 12, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '58.67', 12, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '21.81', 12, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '100.32', 9, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '21.13', 11, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '42.37', 14, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '140.9', 20, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '11.66', 9, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '67.18', 17, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '20.57', 13, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '63.61', 6, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '49.75', 18, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '20.15', 12, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '33.54', 17, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '30.73', 10, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '119.64', 17, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '60.53', 17, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '77.08', 11, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '78.82', 14, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '23.03', 19, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '106.27', 18, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Chino Pants', '66.66', 17, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '123.35', 8, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '67.54', 20, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '139.95', 11, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '64.59', 16, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '18.14', 17, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '57.45', 8, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '169.47', 18, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '65.26', 12, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '8.12', 18, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '24.53', 10, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '78.31', 18, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '56.39', 10, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '92.09', 20, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '66.44', 6, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '47.36', 18, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '24.2', 7, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '102.38', 14, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '196.07', 14, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '116.66', 17, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '87.78', 8, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '120.51', 5, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '11.89', 10, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '157.07', 12, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '39.55', 14, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '18.13', 5, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '20.63', 14, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '28.32', 6, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '39.42', 10, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '74.25', 18, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '85.61', 12, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '24.21', 6, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '23.28', 8, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '136.1', 9, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '36.61', 18, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '28.64', 10, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '37.28', 20, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '174.37', 17, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '48.13', 13, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '165.62', 20, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '29.71', 8, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '56.56', 11, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '51.62', 17, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '147.37', 19, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '39.76', 10, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '109.1', 20, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '100.54', 6, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '74.05', 20, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '15.63', 13, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '48.82', 13, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '144.39', 11, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '148.78', 20, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '37.77', 6, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '35.46', 18, 'Leather Belt', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '57.95', 7, 'Cargo Pants', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '29.63', 6, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '49.87', 13, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '44.3', 9, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '82.51', 15, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '52.5', 8, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '199.71', 15, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '32.55', 20, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '8.87', 13, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '46.84', 20, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '68.76', 13, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '163.75', 11, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '22.51', 10, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '114.89', 8, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '99.75', 20, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '23.41', 9, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '173.6', 20, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '20.76', 6, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '151.66', 15, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '28.71', 14, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '69.69', 19, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '192.9', 17, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '62.19', 7, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '20.47', 16, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '41.99', 9, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '69.29', 17, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '105.91', 11, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Graphic Tee NASA', '39.97', 16, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '66.18', 19, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '12.82', 14, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '53.67', 16, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '91.25', 12, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '158.73', 7, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '78.1', 20, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '27.83', 15, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '142.56', 12, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '28.97', 14, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Fashionable Scarf', '58.56', 16, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '40.15', 14, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '63.91', 5, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '19.04', 18, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '141.42', 10, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Tank Top', '32.56', 11, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '101.5', 20, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '37.38', 9, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '98.79', 17, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '185.02', 6, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '35.39', 10, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '19.39', 17, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '51.84', 15, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '80.77', 19, 'Denim Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Wristwatch', '29.12', 15, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '21.43', 13, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '12.63', 14, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '36.57', 13, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '23.69', 13, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '54.43', 13, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '36.43', 7, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '14.98', 13, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '42.57', 17, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '15.41', 10, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Black Jeans', '98.33', 20, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '146.49', 16, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '21.87', 5, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '86.5', 17, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '174.22', 13, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '79.56', 8, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '47.86', 20, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '148.4', 17, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Windbreaker', '177.95', 16, 'Windbreaker', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '42.49', 12, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '65.06', 7, 'Sneakers', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '37.28', 11, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '14.23', 16, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Wallet', '48.3', 14, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '41.45', 9, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '25.01', 17, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Jogging Shorts', '40.08', 8, 'Trousers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '64.14', 14, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '33.7', 15, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '10.95', 20, 'Long Sleeve Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '49.48', 5, 'Baseball Cap', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Leather Jacket', '177.48', 14, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Parka Coat', '57.28', 11, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bomber Jacket', '149.72', 20, 'Raincoat', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Polo Shirt Classic', '34.31', 5, 'Graphic T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Gold Bracelet', '39.82', 14, 'Sunglasses', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '39.0', 5, 'Wristwatch', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('High-Top Sneakers', '148.51', 19, 'Running Shoes', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Vintage Sunglasses', '24.33', 5, 'Scarf', 'Accessories');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Loafers', '51.34', 6, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '41.56', 20, 'Polo Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '35.02', 18, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Combat Boots', '76.96', 18, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Bermuda Shorts', '57.15', 10, 'Joggers', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '35.41', 18, 'Slim Fit Jeans', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('T-Shirt Spiderman', '26.76', 12, 'Hoodie', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '50.25', 17, 'Puffer Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '34.91', 9, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '104.4', 19, 'Flip Flops', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Workout Leggings', '95.06', 7, 'Shorts', 'Bottom Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '56.82', 13, 'Boots', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Sweater', '10.07', 8, 'Cotton T-Shirt', 'Top Wear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Denim Jacket', '165.34', 20, 'Leather Jacket', 'Outerwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Running Shoes', '116.65', 12, 'Sandals', 'Footwear');
INSERT INTO products(product_name, price, quantity, description, category) VALUES ('Slip-ons', '65.83', 11, 'Sandals', 'Footwear');